config/routes.rb
Rails.application.routes.draw do

  resources :projects do
    resources :tasks
    resources :memberships
  end

  resources :users

  # resources :comments, only: [:create]
  # resources :comments, :only => [:create]

  root "pages#index"

  post 'comments' => 'comments#create'

  #get 'comments' => 'comments#new'

  #match '/investors/new', to: 'investors#new',    via: 'get'
  #post '/task/:task_id/create_comment' => 'tasks#create_comment', as: :task_comments

  get 'about' => 'pages#about', as: :about
  get 'terms' => 'pages#terms', as: :terms
  get 'faq' => 'pages#faq', as: :faq

  get '/sign-up' => 'registrations#new', as: :signup
  post '/sign-up' => 'registrations#create'
  get '/sign-in' => 'authentication#new', as: :signin
  post '/sign-in' => 'authentication#create'
  get '/sign-out' => 'authentication#destroy', as: :signout
  get '/tracker_projects/:id(.:format)' => 'pivotal_stories#show', as: :tracker_project

end

app/models/membership.rb
class Membership < ActiveRecord::Base

  before_destroy :not_last_owner?

  validates :user_id, presence: true, uniqueness: {scope: :project_id, message: "has already been added"}
  validates :role, presence: true

  belongs_to :project
  belongs_to :user
  # enum :role => [ :member, :owner]

  def not_last_owner?
    if self.role == "Member" || project.memberships.where(role: "Owner").count > 1
      true #before_destroy will delete
    else
      false #before_destroy won't delete
    end
  end

end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController

  #always need a project so add the before action with project_id found in rake routes:

  before_action do
    @project = Project.find(params[:project_id])
  end

  before_action :authorize_member
  before_action :authorize_owner, only: [:update]
  # before_action :authorize_current_user_membership

  def index
    @membership = Membership.new
    @memberships = @project.memberships
    #@memberships = Membership.all
  end

  #def new
  #@membership = @project.membership.new
  #end

  def create
    #@membership = @project.memberships.new(membership_params)-- create a new member and associate it with projects -- NO!
    @membership = Membership.new(membership_params)
    @membership.project = @project
    if @membership.save
      redirect_to project_memberships_path(@project), notice: "#{@membership.user.full_name} was added successfully."
    else
      @memberships = @project.memberships
      render :index
    end
  end

  def update
    # add logic here check existing memberships-- to see if there's an owner-- before update action
    @membership = Membership.find(params[:id])
    @membership.update(membership_params)
    redirect_to project_memberships_path, notice: "#{@membership.user.full_name} was updated successfully."
  end


  def destroy
    @membership = Membership.find(params[:id])
    if owner?
      @membership.destroy
      redirect_to project_memberships_path, notice: "#{@membership.user.full_name} was removed successfully."
    elsif current_user == @membership.user
      @membership.destroy
      redirect_to projects_path(@project), notice: "#{@membership.user.full_name} was removed successfully."
    else
      render file: 'public/404', status: :not_found, layout: false
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.

  # Never trust parameters from the scary internet, only allow the white list through.
  def membership_params
    params.require(:membership).permit(:user_id, :project_id, :role)
    #params.require(:membership).permit(:user_id, :title).merge(:project_id => params[:project_id])
  end

  def authorize_member
    @project = Project.find(params[:project_id])
    unless current_user_member?
      render file: 'public/404', status: :not_found, layout: false
    end
  end

  def authorize_owner
    @project = Project.find(params[:project_id])
    unless owner?
      render file: 'public/404', status: :not_found, layout: false
    end
  end

  # def authorize_current_user_membership
  #   @project = Project.find(params[:project_id])
  #   unless current_user_member?
  #     render file: 'public/404', status: :not_found, layout: false
  #   end
  # end

  # def current_user_has_membership?
  #   @membership.user.id == current_user.id
  # end

end

app/views/memberships/index.html.erb
<div class="page-header">
  <h3><%= @project.name %>: Manage Members</h3>
  <ol class="breadcrumb">
    <li><%= link_to "Projects", projects_path %></li>
    <li><%= link_to @project.name, project_path(@project) %></li>
    <li class="active">Memberships</li>
  </ol>
</div>

<div class="row">
  <div class="col-sm-4">
    <%= render "shared/error", instance: @membership %>
  </div>
</div>

<% if owner? %>
<div class="well form-inline col-sm-5">
  <div class="form-group">
    <%= form_for [@project, @membership] do |f| %>
    <%= f.collection_select :user_id, User.all, :id, :full_name, {include_blank: "Please select a user"}, {class: "form-control"} %>
    <%= f.select :role, ["Member", "Owner"], {include_blank: false}, {class: "form-control"} %>
    <%= f.submit "Add New Member", class: "btn btn-info btn-sm" %>
    <% end %>
  </div>
</div>
<% end %>

<table class="table table-condensed">
  <tbody>

  <% @project.memberships.each do |membership| %>
  <%= form_for [@project, membership] do |f| %>

  <tr>
  <% if owner? && membership.not_last_owner? == true %>
  <td class="col-md-2"><%= link_to membership.user.full_name, user_path(membership.user) %></td>
  <td class="col-md-1"><%= f.select :role, ["Member", "Owner"], {include_blank: false}, {class: "form-control"} %></td>
  <td class="col-md-1"><%= f.submit "Update", class: "btn btn-info btn-sm" %></td>
  <td><%= link_to "", project_membership_path(@project, membership), method: :delete, data: { confirm: 'Are you sure?'}, class: "glyphicon glyphicon-remove" %></td>

  <% elsif owner? && membership.not_last_owner? == false %>
  <td class="col-md-2"><%= link_to membership.user.full_name, user_path(membership.user) %></td>
  <td class="col-md-1"><%= membership.role %></td>
  <td class="col-md-1"></td>
  <td><em>Unable to delete the last owner</em></td>

  <% else %>
  <td class="col-md-2"><%= link_to membership.user.full_name, user_path(membership.user) %></td>
  <td class="col-md-1"><%= membership.role %></td>
  <td class="col-md-1"></td>

  <td>
    <% if current_user.id == membership.user_id %>
    <% if membership.not_last_owner? == true %>
    <%= link_to "", project_membership_path(@project, membership), method: :delete, data: { confirm: 'Are you sure?'}, class: "glyphicon glyphicon-remove" %>
    <% end %>
    <% end %>
  </td>
  <% end %>
</tr>

<% end %>
<% end %>
</tbody>
</table>