config/routes.rb
Rails.application.routes.draw do

  resources :projects do
    resources :tasks
    resources :memberships
  end

  resources :users

  # resources :comments, only: [:create]
  # resources :comments, :only => [:create]

  root "pages#index"

  post 'comments' => 'comments#create'

  #get 'comments' => 'comments#new'

  #match '/investors/new', to: 'investors#new',    via: 'get'
  #post '/task/:task_id/create_comment' => 'tasks#create_comment', as: :task_comments

  get 'about' => 'pages#about', as: :about
  get 'terms' => 'pages#terms', as: :terms
  get 'faq' => 'pages#faq', as: :faq

  get '/sign-up' => 'registrations#new', as: :signup
  post '/sign-up' => 'registrations#create'
  get '/sign-in' => 'authentication#new', as: :signin
  post '/sign-in' => 'authentication#create'
  get '/sign-out' => 'authentication#destroy', as: :signout
  get '/tracker_projects/:id(.:format)' => 'pivotal_stories#show', as: :tracker_project

end

app/models/task.rb
class Task < ActiveRecord::Base

  belongs_to :project
  has_many :comments, dependent: :destroy

  validates :description, presence: true
  validate :check_the_date, on: :create

  def check_the_date
    if date.present? && date < Date.today
      errors.add(:date, "can only be today or later.")
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action do
    @project = Project.find(params[:project_id])
  end

  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :authorize_member

  def index
    @tasks = params[:type] == "incomplete"
    @tasks = @project.tasks.where(complete:false)
    if params[:type] == "all"
      @tasks = @project.tasks.all
    end
  end

  def show
    #@task = @project.tasks.find(params[:id])
    @comment = @task.comments.new
  end

  def new
    @task = @project.tasks.new
  end

  def edit
    @edit_task = true
  end

  def create
    @task = @project.tasks.new(task_params)
    if @task.save
      redirect_to project_tasks_path(@project, @task), notice: 'Task was successfully created.'
    else
      render :new
    end
  end


  def update
    if @task.update(task_params)
      redirect_to project_tasks_path(@project, @task), notice: 'Task was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to project_tasks_path, notice: 'Task was successfully destroyed.'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_task
    @task = @project.tasks.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def task_params
    params.require(:task).permit(:description, :complete, :date)
  end

  def authorize_member
    unless current_user_member?
      render file: 'public/404', status: :not_found, layout: false
    end
  end


end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<div class="page-header">
  <h3><%= title %></h3>
</div>

<%= form_for [@project, @task], html: {class: "form-horizontal"} do |f| %>

<div class="row">
  <div class="col-sm-offset-1 col-sm-4">
    <%= render "shared/error", instance: @task %>
  </div>
</div>

<div class="form-group">
  <%= f.label :description, class: "col-sm-1 control-label" %>
  <div class="col-sm-4">
    <%= f.text_field :description, class: "form-control" %>
  </div>
</div>

<div class="form-group">
  <%= f.label :date, class: "col-sm-1 control-label" %>
  <div class="col-sm-4">
    <%= f.date_field :date, class: "form-control" %>
  </div>
</div>

<% if @edit_task == true %>

<div class="form-group">
  <div class="col-sm-offset-1 col-sm-10">
    <%= f.check_box :complete, class: "checkbox-inline" %>
    <%= f.label :complete %>
  </div>
</div>
<% end %>

<div class="form-group">
  <div class="col-sm-offset-1 col-sm-10">
    <%= f.submit class: 'btn btn-info btn-sm' %>
    <%= link_to "Cancel", project_tasks_path, class: 'btn btn-default btn-sm' %>
  </div>
</div>
<% end %>

app/views/tasks/edit.html.erb
<%= render 'form', title: "Edit Task" %>

<div class="col-sm-offset-1">
  <%= link_to 'Show', project_task_path %> |
  <%= link_to 'Back', project_tasks_path %>
</div>

app/views/tasks/index.html.erb
<div class="page-header">

  <div class="pull-right">
    <%= link_to "All", project_tasks_path(type: "all") %> |
    <%= link_to "Incomplete", project_tasks_path(type: "incomplete") %> |
    <%= link_to 'New Task', new_project_task_path, class: 'btn btn-info btn-sm' %>
  </div>

  <h3>Tasks for <%= @project.name %></h3>

  <ol class="breadcrumb">
    <li><%= link_to "Projects", projects_path %></li>
    <li><%= link_to @project.name, project_path(@project) %></li>
    <li class="active">Tasks</li>
  </ol>
</div>

<table class="table table-condensed">
  <thead>
    <tr>
      <th>Description</th>
      <th>Complete</th>
      <th>Due Date</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
    <tr>
      <td class="col-md-6">
        <%= link_to task.description, project_task_path(@project, task) %>
        <span class="badge"><%= task.comments.count %></span>
      </td>
      <td class="col-md-2"><%= task.complete %></td>
      <td class="col-md-1"><%= task.date.try(:strftime, "%m/%d/%Y") %></td>

      <td class="col-md-3">
        <div class="pull-right">
          <%= link_to 'Edit', edit_project_task_path(@project, task), class: 'btn btn-info btn-xs' %>
          <%= link_to '', project_task_path(@project, task), method: :delete, data: { confirm: 'Are you sure?' },
          class: "glyphicon glyphicon-remove" %>
        </div>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/tasks/new.html.erb
<!-- This is part of application helper example of one without a block: -->
<!-- <%= page_header "New Task" %> -->

<%= render 'form', title: "Create a new task" %>

app/views/tasks/show.html.erb
<div class="page-header">
  <div class="pull-right">
    <%= link_to 'Edit', edit_project_task_path(@project, @task), class: 'btn btn-info btn-sm' %>
    <%= link_to "Cancel", project_tasks_path(@project), class: 'btn btn-default btn-sm' %>
  </div>
  <h3><%= @task.description %></h3>

  <ol class="breadcrumb">
    <li><%= link_to "Projects", projects_path %></li>
    <li><%= link_to @project.name, project_path(@project) %></li>
    <li><%= link_to "Tasks", project_tasks_path(@project) %></li>
    <li class="active">Show</li>
  </ol>
</div>

<p>
  <strong>Due date:</strong>
  <%= @task.date.try(:strftime, "%m/%d/%Y") %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @task.complete %>
</p>

<h4>Comments</h4>
<% @task.comments.all.each do |comment| %>
<div class="row">
  <div class="col-xs-3">
    <% if comment.user == nil %>
    <strong>(deleted user)</strong>
    <% else %>
    <strong><%= link_to comment.user.full_name, user_path(comment.user) %></strong>
    <% end %>
    <div class="text-muted">
      <%= time_ago_in_words(comment.created_at) %> ago
    </div>
  </div>

  <div class="col-xs-9">
    <%= comment.comment %>
  </div>
</div>
<br>
<br>
<% end %>

<% if current_user %>
<%= form_for [@comment], html: {class: "form-horizontal"} do |f| %>

<div class="form-group">
  <div class="col-xs-offset-3 col-xs-9">
    <%= f.text_area :comment, class: "form-control" %>
    <%= hidden_field_tag :task_id, @task.id %>
    <%= hidden_field_tag :project_id, @project.id %>
  </div>
</div>

<div class="form-group">
  <div class="col-xs-offset-3 col-xs-9">
    <%= f.submit "Add Comment", class: 'btn btn-info btn-sm' %>
  </div>
</div>
<% end %>
<% end %>