config/routes.rb
Rails.application.routes.draw do

  resources :projects do
    resources :tasks
    resources :memberships
  end

  resources :users

  # resources :comments, only: [:create]
  # resources :comments, :only => [:create]

  root "pages#index"

  post 'comments' => 'comments#create'

  #get 'comments' => 'comments#new'

  #match '/investors/new', to: 'investors#new',    via: 'get'
  #post '/task/:task_id/create_comment' => 'tasks#create_comment', as: :task_comments

  get 'about' => 'pages#about', as: :about
  get 'terms' => 'pages#terms', as: :terms
  get 'faq' => 'pages#faq', as: :faq

  get '/sign-up' => 'registrations#new', as: :signup
  post '/sign-up' => 'registrations#create'
  get '/sign-in' => 'authentication#new', as: :signin
  post '/sign-in' => 'authentication#create'
  get '/sign-out' => 'authentication#destroy', as: :signout
  get '/tracker_projects/:id(.:format)' => 'pivotal_stories#show', as: :tracker_project

end

app/models/project.rb
class Project < ActiveRecord::Base

  has_many :memberships, dependent: :destroy
  has_many :tasks, dependent: :destroy

  has_many :users, through: :memberships

  validates :name, presence: true

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authorize_member, only: [:show]
  before_action :authorize_owner, only: [:edit, :update, :destroy]

  def index
    @projects = Project.all
    #instantiate an instance of the TrackerAPI class. tracker_api variable is instance of the class
    #tracker_api is not an instance variable since it doesn't need to be displayed in the view
    tracker_api = TrackerAPI.new
    #calling the method and passing it a token
    #pass things down to views with an instance variable
    #this is client code
    @tracker_projects = tracker_api.projects(current_user.pivotal_tracker_token)
  end

  def new
    @project = Project.new
  end

  def create
    project_params=params.require(:project).permit(:name)
    @project = Project.new(project_params)
    if @project.save
      redirect_to project_tasks_path(@project), notice: "Project was successfully created."
      Membership.create(project_id: @project.id, user_id: current_user.id, role: "Owner")
    else
      render :new
    end
  end

  def show
    @project = Project.find(params[:id])
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    project_params = params.require(:project).permit(:name)
    @project = Project.find(params[:id])
    if @project.update(project_params)
      redirect_to project_path(@project), notice: "Project was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @project = Project.find(params[:id])
    if @project.destroy
      flash[:success]="Project was successfully deleted."
      redirect_to projects_path
    end
  end

  private

  def authorize_member
    @project = Project.find(params[:id])
    unless current_user_member?
      render file: 'public/404', status: :not_found, layout: false
    end
  end

  def authorize_owner
    @project = Project.find(params[:id])
    unless owner?
      render file: 'public/404', status: :not_found, layout: false
    end
  end

  # def project_params
  #   params.required(:project).permit(:name)
  # end

end

app/views/projects/_form.html.erb
<div class="page-header">
  <h3><%= title %></h3>
</div>

<%= form_for(@project, html: {class: "form-horizontal"}) do |f| %>

<div class="row">
  <div class="col-sm-offset-1 col-sm-4">
    <%= render "shared/error", instance: @project %>
  </div>
</div>

<div class="form-group">
  <%= f.label :name, class: "col-sm-1" %>
  <div class="col-sm-4">
    <%= f.text_field :name, class: "form-control" %>
  </div>
</div>

<div class="form-group">
  <div class="col-sm-offset-1 col-sm-10">
    <%= f.submit class: "btn btn-info btn-sm" %>
    <%= link_to "Cancel", projects_path, class: 'btn btn-default btn-sm' %>
  </div>
</div>

<% end %>

app/views/projects/edit.html.erb
<%= render "form", title: "Edit Project" %>

app/views/projects/index.html.erb
<!-- This is an application helper with capture block:  -->
<%= page_header "My Projects" do %>
<%= link_to "Create Project", new_project_path, :class => "btn btn-info btn-sm" %>
<% end %>


<!-- <div class="page-header">
  <div class="pull-right">
      <%= link_to "Create Project", new_project_path, :class => "btn btn-info btn-sm" %>
  </div>
<h3>My Projects</h3>
</div> -->



<table class="table table-condensed">
  <thead>
    <tr>
    <th width="40%">Name</th>
    <th width="30%">Members</th>
    <th width="30%">Tasks</th>
    </tr>
  </thead>

  <tbody>
    <% current_user.projects.each do |project| %>
    <tr>
      <td><%= link_to project.name, project_path(project) %></td>
      <td><%= link_to (project.memberships.count), project_memberships_path(project) %></td>
      <td><%= link_to (project.tasks.count), project_tasks_path(project) %></td>
    </tr>
    <% end %>
  </tbody>
</table>


<% if current_user.pivotal_tracker_token.present? %>

<div class="page-header">
  <h3>Pivotal Tracker Projects</h3>
</div>

<table class="table table-condensed">
  <thead>
    <tr>
      <th width="40%">Name</th>
    </tr>
  </thead>

  <tbody>
    <% @tracker_projects.each do |project| %>
    <tr>
      <td><%= link_to project.name, tracker_project_path(project.id) %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<% end %>

app/views/projects/new.html.erb
<%= render "form", title: "Create Project" %>

app/views/projects/show.html.erb
<div class="page-header">

  <% if owner? %>
  <div class="pull-right">
    <%= link_to "edit", edit_project_path(@project), :class => "btn btn-info btn-sm" %>
    <%= link_to "delete", project_path(@project), method: :delete, :class => "btn btn-danger btn-sm" %>
  </div>
  <% end %>

  <h3><%= @project.name %></h3>
</div>

<ol class="breadcrumb">
  <li><%= link_to "Projects", projects_path %></li>
  <li class="active">Tasks</li>
</ol>
<%= link_to pluralize(@project.tasks.count, "Task"), project_tasks_path(@project) %><br>
<%= link_to pluralize(@project.memberships.count, "Member"), project_memberships_path(@project) %>
<br><br>

<% if owner? %>
<div class="well">
  <strong><p>Delete Project</p></strong>
  <p>Deleting this project will also delete <%= pluralize(@project.memberships.count, "membership") %>, <%= pluralize(@project.tasks.count, "task") %> and associated comments.</p>
  <%= link_to 'Delete', project_path(id: @project.id), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
</div>
<% end %>