config/routes.rb
Rails.application.routes.draw do

  resources :projects do
    resources :tasks
    resources :memberships
  end

  resources :users

  # resources :comments, only: [:create]
  # resources :comments, :only => [:create]

  root "pages#index"

  post 'comments' => 'comments#create'

  #get 'comments' => 'comments#new'

  #match '/investors/new', to: 'investors#new',    via: 'get'
  #post '/task/:task_id/create_comment' => 'tasks#create_comment', as: :task_comments

  get 'about' => 'pages#about', as: :about
  get 'terms' => 'pages#terms', as: :terms
  get 'faq' => 'pages#faq', as: :faq

  get '/sign-up' => 'registrations#new', as: :signup
  post '/sign-up' => 'registrations#create'
  get '/sign-in' => 'authentication#new', as: :signin
  post '/sign-in' => 'authentication#create'
  get '/sign-out' => 'authentication#destroy', as: :signout
  get '/tracker_projects/:id(.:format)' => 'pivotal_stories#show', as: :tracker_project

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <%= stylesheet_link_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag 'application' %>


  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- <title>gCamp</title> -->

  <title><%= content_for(:title) || "gCamp" %></title>

</head>

<body>

  <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <!-- <div class="navbar-header"> -->
      <%= link_to "gCamp", projects_path, class:"navbar-brand" %>


    <ul class="nav navbar-nav">
      <li class="dropdown">
        <a href="/projects" class="dropdown-toggle" data-toggle="dropdown">
          My Projects
          <span class="caret"></span>
        </a>
        <ul class="dropdown-menu" role="menu">


          <% current_user.projects.each do |project| %>
          <li><%= link_to project.name, project_path(project) %></li>
          <% end %>

          <li class="divider"></li>
          <li><%= link_to "New Project", new_project_path %></li>
        </ul>
      </li>
      <li><%= link_to "Users", users_path %></li>
    </ul>


    <ul class="nav navbar-nav navbar-right">
      <% if current_user %>
      <li><%= link_to current_user.full_name, user_path(current_user) %></li>
      <li><%= link_to "Sign Out", signout_path %></li>
      <% else %>
      <li><%= link_to "Sign Up", signup_path %></li>
      <li><%= link_to "Sign In", signin_path %></li>
      <% end %>
    </ul>
  </div>
</div>

<!-- Main jumbotron for a primary marketing message or call to action -->


<div class="container">

  <% if flash[:success] %>
  <div class="alert alert-success" role="alert">
    <%= flash[:success] %>
  </div>
  <% end %>

  <% if flash[:notice] %>
  <div class="alert alert-info" role="alert">
    <%= flash[:notice] %>
  </div>
  <% end %>

  <%= yield %>
  <br>
</div>

<footer>
  <div class="container">
    <hr>
    <div class="center">
      <div class="col-sm-offset-5 col-md-12">
        <%= link_to "Home", root_path %> |
        <%= link_to "About", about_path %>  |
        <%= link_to "Terms", terms_path %> |
        <%= link_to "FAQ", faq_path %>
      </div>

    </div>
  </div>
</footer>
<!-- /container -->
<br>
</body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <%= stylesheet_link_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag 'application' %>


  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <!-- <link rel="icon" href="../../favicon.ico"> -->

  <title>gCamp</title>




  <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
  <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
  <!-- <script src="../../assets/js/ie-emulation-modes-warning.js"></script> -->

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

</head>

<body>

  <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <!-- <a class="navbar-brand" href="#">gCamp</a> -->
        <%= link_to "gCamp", root_path, class:"navbar-brand" %>
      </div>

      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
        <li><%= link_to current_user.full_name, user_path(current_user) %></li>
        <li><%= link_to "Sign Out", signout_path %></li>
        <% else %>
        <li><%= link_to "Sign Up", signup_path %></li>
        <li><%= link_to "Sign In", signin_path %></li>
        <% end %>
      </ul>
    </div>
  </div>

  <!-- Main jumbotron for a primary marketing message or call to action -->


  <div class="container">

    <% if flash[:success] %>
    <div class="alert alert-success" role="alert">
      <%= flash[:success] %>
    </div>
    <% end %>

    <% if flash[:notice] %>
    <div class="alert alert-info" role="alert">
      <%= flash[:notice] %>
    </div>
    <% end %>

    <%= yield %>
    <br>
  </div>

  <footer>
    <div class="container">
      <hr>
      <div class="row">
        <div class="col-md-6">
          <%= link_to "Home", root_path %> |
          <%= link_to "About", about_path %>  |
          <%= link_to "Terms", terms_path %> |
          <%= link_to "FAQ", faq_path %>

          <% if current_user %>
          | <%= link_to "My Projects", projects_path %>
          <% end %>
        </div>

          <div class="pull-right">
            <%= link_to "www.linkedin.com/pub/kendra-dodds/70/b47/413/" do %>
            <%= image_tag("linkedinLogo.png", width: "20em") %>
            <% end %>

            <%= link_to "https://github.com/ardnek" do %>
            <%= image_tag("githubLogo.png", width: "20em") %>
            <% end %>

            <%= link_to "https://twitter.com/kendradodds" do %>
            <%= image_tag("twitterLogo.png", width: "20em") %>
            <% end %>

            <%= link_to "https://students.gschool.it/students/104" do %>
            <%= image_tag("gschool.png", width: "20em") %>
            <% end %>
          </div>
      </div>
    </div>
  </footer>
  <!-- /container -->

  <br>
</body>
</html>